from . import brand_model
from . import brand
from . import complaint_service_relation
from . import complaint
from . import compliant_description
from . import product_order_line
from . import product
from . import res_partner
from . import service_ticket
from . import service
from . import term_condition
from . import warranty
from . import mobile_servicece_crm